import { chromium } from 'playwright-core';
import { existsSync } from 'node:fs';
const EXE = ['C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe'].find(p=>existsSync(p));
const b = await chromium.launch({ executablePath:EXE, headless:true, args:['--use-gl=angle','--enable-unsafe-swiftshader'] });
const page = await (await b.newContext({viewport:{width:900,height:600}})).newPage();
page.on('pageerror',e=>console.log('PAGEERROR:', e.message.slice(0,300)));
page.on('console', m=>{ if(m.type()==='error') console.log('CONSOLE:', m.text().slice(0,300)); });
await page.goto(process.env.TARGET, { waitUntil:'networkidle', timeout:40000 });
await page.click('#btn-start');
await page.waitForTimeout(9000);
console.log('__yc?', await page.evaluate(()=>typeof window.__yc));
await b.close();
